# Cox Proportional Hazards

### Wstęp
&emsp;Model proporcjonalnego hazardu Cox'a jest modelem pozwalającym ocenić wpływ wielu czynników na funkcję hazardu (chwilowe natężenie ryzyka). W naszym przypadku oceniać będziemy wpływ na ryzyko zapłaty (zdarzenie).

&emsp; Przy budownie modelu uwzględnimy następujące cechy:
* `total_open_amount` *(kwota faktury)*
* `days_to_due` *(po ilu dniach płatność)*
* `invoice_age` *(wiek faktury)*
* `avg_delay_customer` *(średnie opóźnienie klienta)*
* `cust_payment_terms` *(warunki płatności)*
* `invoice_currency` *(waluta)*
* `segment` *(BE lub SME)*

### Biblioteki i przygotowanie danych
&emsp; Zacznijmy od zaimportowania niezbędnych narzędzi oraz przygotowania danych. Zostawimy jedynie kolumny odpowiadające interesującym nas cechom.

In [64]:
import pandas as pd
from lifelines import CoxPHFitter
import matplotlib.pyplot as plt

df = pd.read_csv('../data/dataset_survclean.csv')

df['document_create_date_dt'] = pd.to_datetime(df['document_create_date_dt'])
df = df.sort_values('document_create_date_dt')

features = [
    'total_open_amount',
    'days_to_due',
    'invoice_age',
    'avg_delay_customer',
    'cust_payment_terms',
    'invoice_currency',
    'segment',
    'time_days', 
    'event'
]

cox_df = df[features].copy()

cox_df = pd.get_dummies(cox_df, columns=['cust_payment_terms', 'invoice_currency', 'segment'], drop_first=True)
cox_df = cox_df.dropna()
cox_df = cox_df.astype(float)

splt_id = int(len(cox_df) * 0.8)
train_df = cox_df.iloc[:splt_id]
test_df = cox_df.iloc[splt_id:]

print(f"Zbiór treningowy: {len(train_df)} faktur\nZbiór testowy: {len(test_df)} faktur")

display(train_df.head())

Zbiór treningowy: 39070 faktur
Zbiór testowy: 9768 faktur

,total_open_amount,days_to_due,invoice_age,avg_delay_customer,time_days,event,cust_payment_terms_NA10,cust_payment_terms_NA32,cust_payment_terms_NAA8,cust_payment_terms_NAAW,...,cust_payment_terms_NAVF,cust_payment_terms_NAVQ,cust_payment_terms_NAVR,cust_payment_terms_NAWN,cust_payment_terms_NAWP,cust_payment_terms_NAWU,cust_payment_terms_NAX2,cust_payment_terms_OTHER,invoice_currency_USD,segment_SME
0,13760.55,34.0,30.0,0.0,28.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1,28225.48,32.0,30.0,0.0,62.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
53,4445.93,16.0,15.0,0.2,11.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
52,51473.49,16.0,15.0,0.0,17.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
51,4678.12,20.0,15.0,0.0,19.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Model
&emsp; Pozostało dopasować model Coxa do badanego zbioru danych. Kolumną zawierającą informacje na temat upływu czasu jest `time_days`, a kolumną informującą o wystąpieniu zdarzenia jest kolumna `event`.

In [65]:
cph = CoxPHFitter(penalizer=0.1)
const_cols = [c for c in train_df.columns 
              if c not in ('time_days', 'event') and train_df[c].std() == 0]
train_df = train_df.drop(columns=const_cols)

cph.fit(train_df, duration_col='time_days', event_col='event')

#### Załozenie o proporcjinalności hazardów
&emsp; Model Coxa opiera się na załozeniu o proporcjonalności hazardów. Załozenie to mowi, ze stosunek hazardu dla dowolnych dwoch obserwacji musi być stały w czasie. W kontekście projektu oznacza to, ze wpływ cechy na prawdopodobieństwo zapłacenia faktury nie moze się zmieniać wraz upływem dni. Wpływ ten musi być ponadto liniowy.

&emsp; Jeśli to załozenie jest łamane model traci na wiarygodności. W celu jego weryfikacji wykorzystamy test reszt Schoenfelda.

In [66]:
results = cph.check_assumptions(train_df, p_value_threshold=0.05, show_plots=False)

The ``p_value_threshold`` is set at 0.05. Even under the null hypothesis of no violations, some
covariates will be below the threshold by chance. This is compounded when there are many covariates.
Similarly, when there are lots of observations, even minor deviances from the proportional hazard
assumption will be flagged.

With that in mind, it's best to use a combination of statistical tests and visual tests to determine
the most serious violations. Produce visual plots using ``check_assumptions(..., show_plots=True)``
and looking for non-constant lines. See link [A] below for a full example.

1. Variable 'total_open_amount' failed the non-proportional test: p-value is <5e-05.

   Advice 1: the functional form of the variable 'total_open_amount' might be incorrect. That is,
there may be non-linear terms missing. The proportional hazard test used is very sensitive to
incorrect functional forms. See documentation in link [D] below on how to specify a functional form.

   Advice 2: try binning the variable 'total_open_amount' using pd.cut, and then specify it in
`strata=['total_open_amount', ...]` in the call in `.fit`. See documentation in link [B] below.

   Advice 3: try adding an interaction term with your time variable. See documentation in link [C]
below.


2. Variable 'days_to_due' failed the non-proportional test: p-value is <5e-05.

   Advice 1: the functional form of the variable 'days_to_due' might be incorrect. That is, there
may be non-linear terms missing. The proportional hazard test used is very sensitive to incorrect
functional forms. See documentation in link [D] below on how to specify a functional form.

   Advice 2: try binning the variable 'days_to_due' using pd.cut, and then specify it in
`strata=['days_to_due', ...]` in the call in `.fit`. See documentation in link [B] below.

   Advice 3: try adding an interaction term with your time variable. See documentation in link [C]
below.


3. Variable 'avg_delay_customer' failed the non-proportional test: p-value is <5e-05.

   Advice 1: the functional form of the variable 'avg_delay_customer' might be incorrect. That is,
there may be non-linear terms missing. The proportional hazard test used is very sensitive to
incorrect functional forms. See documentation in link [D] below on how to specify a functional form.

   Advice 2: try binning the variable 'avg_delay_customer' using pd.cut, and then specify it in
`strata=['avg_delay_customer', ...]` in the call in `.fit`. See documentation in link [B] below.

   Advice 3: try adding an interaction term with your time variable. See documentation in link [C]
below.


4. Variable 'cust_payment_terms_NA10' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NA10',
...]` in the call in `.fit`. See documentation in link [E] below.

5. Variable 'cust_payment_terms_NA32' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NA32',
...]` in the call in `.fit`. See documentation in link [E] below.

6. Variable 'cust_payment_terms_NAA8' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAA8',
...]` in the call in `.fit`. See documentation in link [E] below.

7. Variable 'cust_payment_terms_NAAW' failed the non-proportional test: p-value is 0.0322.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAAW',
...]` in the call in `.fit`. See documentation in link [E] below.

8. Variable 'cust_payment_terms_NAAX' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAAX',
...]` in the call in `.fit`. See documentation in link [E] below.

9. Variable 'cust_payment_terms_NAC6' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAC6',
...]` in the call in `.fit`. See documentation in link [E] below.

10. Variable 'cust_payment_terms_NAD1' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAD1',
...]` in the call in `.fit`. See documentation in link [E] below.

11. Variable 'cust_payment_terms_NAGD' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAGD',
...]` in the call in `.fit`. See documentation in link [E] below.

12. Variable 'cust_payment_terms_NAH4' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAH4',
...]` in the call in `.fit`. See documentation in link [E] below.

13. Variable 'cust_payment_terms_NAM1' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAM1',
...]` in the call in `.fit`. See documentation in link [E] below.

14. Variable 'cust_payment_terms_NAM2' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAM2',
...]` in the call in `.fit`. See documentation in link [E] below.

15. Variable 'cust_payment_terms_NAM4' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAM4',
...]` in the call in `.fit`. See documentation in link [E] below.

16. Variable 'cust_payment_terms_NAU5' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAU5',
...]` in the call in `.fit`. See documentation in link [E] below.

17. Variable 'cust_payment_terms_NAVE' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAVE',
...]` in the call in `.fit`. See documentation in link [E] below.

18. Variable 'cust_payment_terms_NAVF' failed the non-proportional test: p-value is 0.0150.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAVF',
...]` in the call in `.fit`. See documentation in link [E] below.

19. Variable 'cust_payment_terms_NAVQ' failed the non-proportional test: p-value is 0.0002.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAVQ',
...]` in the call in `.fit`. See documentation in link [E] below.

20. Variable 'cust_payment_terms_NAVR' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAVR',
...]` in the call in `.fit`. See documentation in link [E] below.

21. Variable 'cust_payment_terms_NAWN' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAWN',
...]` in the call in `.fit`. See documentation in link [E] below.

22. Variable 'cust_payment_terms_NAX2' failed the non-proportional test: p-value is 0.0431.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_NAX2',
...]` in the call in `.fit`. See documentation in link [E] below.

23. Variable 'cust_payment_terms_OTHER' failed the non-proportional test: p-value is 0.0003.

   Advice: with so few unique values (only 2), you can include `strata=['cust_payment_terms_OTHER',
...]` in the call in `.fit`. See documentation in link [E] below.

24. Variable 'segment_SME' failed the non-proportional test: p-value is <5e-05.

   Advice: with so few unique values (only 2), you can include `strata=['segment_SME', ...]` in the
call in `.fit`. See documentation in link [E] below.

---
[A]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html
[B]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html#Bin-variable-and-stratify-on-it
[C]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html#Introduce-time-varying-covariates
[D]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html#Modify-the-functional-form
[E]  https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html#Stratification

&emsp;Z tabeli odczytujemy, że dla wielu zmiennych (m.in. `avg_delay_customer`, `days_to_due`, `invoice_age`, `segment_SME`, `total_open_amount`), wartość p-value jest niższa niż próg 0.05. Oznacza to, że hipoteza zerowa testu Schoenfelda jest fałszywa. Co za tym idzie, wpływ cech na "ryzyko" opłacenia faktury nie jest stały w czasie.

&emsp;Mamy do czynienia ze złamaniem podstawowego założenia modelu Coxa, co pozwala wyciągnąć wniosek, że modele nieliniowe jak Random Survival Forest poradzą sobie z predykcją zauważalnie lepiej.

#### Ewaluacja modelu
&emsp; Bazując na budowie algorytmu do wyliczenia funkcji częściowej wiarygodności (partial likelihood), w której wzorze wspolczynnik dla kazdej cechy jest stały w czasie, otrzymane w tabeli wyniki mozemy interpretować jako uśredniowy wpływ poszczególnych cech na "ryzyko"" zapłaty.

&emsp; Wywołanie `cph.print_summary` dostarczy nam informacji o m.in:
* Hazard Ratio (`exp(coef)`): Dla zmiennych kategorycznych stosunek hazardu między podmiotem posiadającym i nieposiadającym danej cechy. Dla zmiennych ciągłych zmiana intensywności spłaty przy wzroście cechy o jedną jednostkę. Interpretacja:
    * HR > 1: zwiększone ryzyko
    * HR = 1: brak wpływu
    * HR < 1: zmniejszone ryzyko
* C-index (`Concordance`): Odsetek par, które model poprawnie uporządkował pod względem czasu do wystąpienia zdarzenia.

In [67]:
cph.print_summary()
test_cid = cph.score(test_df, scoring_method="concordance_index")

print(f"test C-index: {test_cid: .4f}")

<lifelines.CoxPHFitter: fitted with 39070 total observations, 38 right-censored observations>
             duration col = 'time_days'
                event col = 'event'
                penalizer = 0.1
                 l1 ratio = 0.0
      baseline estimation = breslow
   number of observations = 39070
number of events observed = 39032
   partial log-likelihood = -361779.38
         time fit was run = 2026-09-21 16:57:06 UTC

---
                          coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
total_open_amount         0.00      1.00      0.00            0.00            0.00                1.00                1.00
days_to_due              -0.04      0.96      0.00           -0.04           -0.04                0.96                0.97
invoice_age              -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
avg_delay_customer       -0.03      0.97      0.00           -0.04           -0.03                0.96                0.97
cust_payment_terms_NA10  -0.19      0.83      0.05           -0.29           -0.08                0.74                0.92
cust_payment_terms_NA32  -0.75      0.47      0.04           -0.84           -0.66                0.43                0.52
cust_payment_terms_NAA8  -0.28      0.76      0.02           -0.32           -0.24                0.73                0.79
cust_payment_terms_NAAW   0.16      1.18      0.08            0.01            0.32                1.01                1.38
cust_payment_terms_NAAX  -0.08      0.93      0.04           -0.15           -0.01                0.86                0.99
cust_payment_terms_NAC6  -0.13      0.88      0.03           -0.19           -0.07                0.82                0.93
cust_payment_terms_NAD1  -0.69      0.50      0.04           -0.76           -0.61                0.47                0.54
cust_payment_terms_NAD5  -0.87      0.42      0.06           -0.99           -0.75                0.37                0.47
cust_payment_terms_NAG2  -0.85      0.43      0.04           -0.93           -0.76                0.39                0.47
cust_payment_terms_NAGD  -0.23      0.80      0.06           -0.35           -0.10                0.71                0.90
cust_payment_terms_NAH4   0.36      1.43      0.02            0.32            0.40                1.38                1.49
cust_payment_terms_NAM1   3.81     44.94      0.09            3.63            3.98               37.90               53.28
cust_payment_terms_NAM2   3.85     46.79      0.06            3.72            3.97               41.30               53.01
cust_payment_terms_NAM4   2.13      8.44      0.04            2.06            2.21                7.84                9.09
cust_payment_terms_NAU5  -0.13      0.88      0.04           -0.20           -0.05                0.81                0.96
cust_payment_terms_NAVE  -0.80      0.45      0.07           -0.94           -0.67                0.39                0.51
cust_payment_terms_NAVF  -0.59      0.55      0.08           -0.74           -0.45                0.48                0.64
cust_payment_terms_NAVQ  -0.46      0.63      0.11           -0.67           -0.25                0.51                0.78
cust_payment_terms_NAVR   0.23      1.26      0.13           -0.02            0.48                0.98                1.61
cust_payment_terms_NAWN  -0.26      0.77      0.11           -0.48           -0.03                0.62                0.97
cust_payment_terms_NAWP  -0.78      0.46      0.12           -1.01           -0.55                0.36                0.58
cust_payment_terms_NAWU  -0.69      0.50      0.09           -0.87           -0.51                0.42                0.60
cust_payment_terms_NAX2  -1.04      0.35      0.06           -1.16           -0.93                0.31                0.39
cust_payment_terms_OTHER -0.50      0.61      0.05           -0.59           -0.40                0.55                0.67
invoice_currency_USD      0.44      1.55      0.03            0.39            0.49                1.47                1.63
segment_SME              -0.11      0.90      0.01           -0.14           -0.08                0.87                0.92

                          cmp to      z      p  -log2(p)
covariate
total_open_amount           0.00  14.90 <0.005    164.38
days_to_due                 0.00 -38.76 <0.005       inf
invoice_age                 0.00  -0.08   0.94      0.09
avg_delay_customer          0.00 -33.89 <0.005    834.14
cust_payment_terms_NA10     0.00  -3.42 <0.005     10.64
cust_payment_terms_NA32     0.00 -16.93 <0.005    211.19
cust_payment_terms_NAA8     0.00 -14.19 <0.005    149.37
cust_payment_terms_NAAW     0.00   2.03   0.04      4.55
cust_payment_terms_NAAX     0.00  -2.12   0.03      4.90
cust_payment_terms_NAC6     0.00  -4.09 <0.005     14.49
cust_payment_terms_NAD1     0.00 -18.44 <0.005    249.77
cust_payment_terms_NAD5     0.00 -14.44 <0.005    154.65
cust_payment_terms_NAG2     0.00 -19.70 <0.005    284.71
cust_payment_terms_NAGD     0.00  -3.64 <0.005     11.81
cust_payment_terms_NAH4     0.00  17.50 <0.005    225.47
cust_payment_terms_NAM1     0.00  43.77 <0.005       inf
cust_payment_terms_NAM2     0.00  60.35 <0.005       inf
cust_payment_terms_NAM4     0.00  56.32 <0.005       inf
cust_payment_terms_NAU5     0.00  -3.09 <0.005      8.96
cust_payment_terms_NAVE     0.00 -11.96 <0.005    107.08
cust_payment_terms_NAVF     0.00  -7.88 <0.005     48.12
cust_payment_terms_NAVQ     0.00  -4.23 <0.005     15.41
cust_payment_terms_NAVR     0.00   1.77   0.08      3.72
cust_payment_terms_NAWN     0.00  -2.26   0.02      5.39
cust_payment_terms_NAWP     0.00  -6.55 <0.005     33.99
cust_payment_terms_NAWU     0.00  -7.53 <0.005     44.22
cust_payment_terms_NAX2     0.00 -18.11 <0.005    240.99
cust_payment_terms_OTHER    0.00 -10.03 <0.005     76.25
invoice_currency_USD        0.00  17.11 <0.005    215.53
segment_SME                 0.00  -7.32 <0.005     41.86
---
Concordance = 0.77
Partial AIC = 723618.76
log-likelihood ratio test = 24069.07 on 30 df
-log2(p) of ll-ratio test = inf

test C-index:  0.4404

In [68]:
print(f"odsetek zdarzeń — trening: {train_df['event'].mean():.3f}, test: {test_df['event'].mean():.3f}")
print(f"C-index — trening: {cph.score(train_df, scoring_method='concordance_index'):.4f}, "
      f"test: {test_cid:.4f}")

odsetek zdarzeń — trening: 0.999, test: 0.013
C-index — trening: 0.7720, test: 0.4404

### Sprawdźmy inny podział

In [71]:
splt_id = int(len(cox_df) * 0.5)
train_df = cox_df.iloc[:splt_id]
test_df = cox_df.iloc[splt_id:]

print(f"Zbiór treningowy: {len(train_df)} faktur\nZbiór testowy: {len(test_df)} faktur")

Zbiór treningowy: 24419 faktur
Zbiór testowy: 24419 faktur

In [74]:
const_cols = [c for c in train_df.columns 
              if c not in ('time_days', 'event') and train_df[c].std() == 0]
train_df = train_df.drop(columns=const_cols)
cph.fit(train_df, duration_col='time_days', event_col='event')

cph.print_summary()
test_cid = cph.score(test_df, scoring_method="concordance_index")

print(f"test C-index: {test_cid: .4f}")

<lifelines.CoxPHFitter: fitted with 24419 total observations, 0 right-censored observations>
             duration col = 'time_days'
                event col = 'event'
                penalizer = 0.1
                 l1 ratio = 0.0
      baseline estimation = breslow
   number of observations = 24419
number of events observed = 24419
   partial log-likelihood = -214911.02
         time fit was run = 2026-09-21 17:01:56 UTC

---
                          coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
total_open_amount         0.00      1.00      0.00            0.00            0.00                1.00                1.00
days_to_due              -0.03      0.97      0.00           -0.04           -0.03                0.97                0.97
invoice_age              -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
avg_delay_customer       -0.03      0.97      0.00           -0.03           -0.03                0.97                0.97
cust_payment_terms_NA10  -0.21      0.81      0.07           -0.34           -0.07                0.71                0.93
cust_payment_terms_NA32  -0.75      0.47      0.06           -0.86           -0.64                0.43                0.53
cust_payment_terms_NAA8  -0.25      0.78      0.02           -0.29           -0.20                0.74                0.82
cust_payment_terms_NAAW   0.11      1.12      0.10           -0.08            0.31                0.92                1.36
cust_payment_terms_NAAX  -0.05      0.95      0.04           -0.14            0.03                0.87                1.03
cust_payment_terms_NAC6  -0.07      0.93      0.04           -0.15            0.01                0.86                1.01
cust_payment_terms_NAD1  -0.64      0.53      0.05           -0.73           -0.55                0.48                0.58
cust_payment_terms_NAD5  -0.88      0.42      0.07           -1.02           -0.73                0.36                0.48
cust_payment_terms_NAG2  -0.86      0.42      0.05           -0.96           -0.75                0.38                0.47
cust_payment_terms_NAGD  -0.30      0.74      0.07           -0.44           -0.16                0.64                0.85
cust_payment_terms_NAH4   0.36      1.44      0.03            0.31            0.41                1.37                1.51
cust_payment_terms_NAM1   3.88     48.53      0.11            3.66            4.10               38.93               60.50
cust_payment_terms_NAM2   3.88     48.62      0.08            3.72            4.05               41.35               57.17
cust_payment_terms_NAM4   2.12      8.32      0.05            2.02            2.21                7.56                9.15
cust_payment_terms_NAU5  -0.13      0.88      0.05           -0.22           -0.03                0.80                0.97
cust_payment_terms_NAVE  -0.83      0.44      0.08           -1.00           -0.67                0.37                0.51
cust_payment_terms_NAVF  -0.65      0.52      0.09           -0.83           -0.48                0.44                0.62
cust_payment_terms_NAVQ  -0.49      0.61      0.13           -0.74           -0.23                0.48                0.80
cust_payment_terms_NAVR   0.10      1.11      0.13           -0.16            0.37                0.85                1.44
cust_payment_terms_NAWN  -0.35      0.71      0.12           -0.59           -0.11                0.56                0.90
cust_payment_terms_NAWP  -0.83      0.44      0.17           -1.16           -0.49                0.31                0.61
cust_payment_terms_NAX2  -1.08      0.34      0.07           -1.21           -0.94                0.30                0.39
cust_payment_terms_OTHER -0.54      0.59      0.06           -0.65           -0.42                0.52                0.66
invoice_currency_USD      0.46      1.58      0.03            0.40            0.52                1.48                1.68
segment_SME              -0.10      0.90      0.02           -0.14           -0.07                0.87                0.93

                          cmp to      z      p  -log2(p)
covariate
total_open_amount           0.00  13.39 <0.005    133.33
days_to_due                 0.00 -28.94 <0.005    609.38
invoice_age                 0.00  -1.34   0.18      2.47
avg_delay_customer          0.00 -26.31 <0.005    504.35
cust_payment_terms_NA10     0.00  -2.99 <0.005      8.48
cust_payment_terms_NA32     0.00 -13.31 <0.005    131.95
cust_payment_terms_NAA8     0.00  -9.84 <0.005     73.53
cust_payment_terms_NAAW     0.00   1.12   0.26      1.93
cust_payment_terms_NAAX     0.00  -1.21   0.23      2.15
cust_payment_terms_NAC6     0.00  -1.72   0.09      3.55
cust_payment_terms_NAD1     0.00 -13.70 <0.005    139.52
cust_payment_terms_NAD5     0.00 -12.17 <0.005    110.77
cust_payment_terms_NAG2     0.00 -15.98 <0.005    188.50
cust_payment_terms_NAGD     0.00  -4.14 <0.005     14.79
cust_payment_terms_NAH4     0.00  13.99 <0.005    145.22
cust_payment_terms_NAM1     0.00  34.53 <0.005    865.37
cust_payment_terms_NAM2     0.00  47.00 <0.005       inf
cust_payment_terms_NAM4     0.00  43.43 <0.005       inf
cust_payment_terms_NAU5     0.00  -2.54   0.01      6.48
cust_payment_terms_NAVE     0.00  -9.91 <0.005     74.43
cust_payment_terms_NAVF     0.00  -7.26 <0.005     41.20
cust_payment_terms_NAVQ     0.00  -3.70 <0.005     12.20
cust_payment_terms_NAVR     0.00   0.76   0.45      1.16
cust_payment_terms_NAWN     0.00  -2.85 <0.005      7.84
cust_payment_terms_NAWP     0.00  -4.87 <0.005     19.77
cust_payment_terms_NAX2     0.00 -15.46 <0.005    176.66
cust_payment_terms_OTHER    0.00  -8.86 <0.005     60.18
invoice_currency_USD        0.00  14.22 <0.005    149.97
segment_SME                 0.00  -5.60 <0.005     25.52
---
Concordance = 0.77
Partial AIC = 429880.04
log-likelihood ratio test = 14767.92 on 29 df
-log2(p) of ll-ratio test = inf

test C-index:  0.6133